Fix iterator constructor and other failing tests
BioJulia/Kmers.jl pull request #32
Opened 2023-03-01 03:41 UTC by cjprybol

Fixes https://github.com/BioJulia/BioSequences.jl/issues/270 but depends on https://github.com/BioJulia/BioSequences.jl/pull/271 in order to pass all tests

```bash
$ julia runtests.jl 
Test Summary:          | Pass  Total
BioSequences Interface |    8      8
Test Summary:                | Pass  Total
Construction and Conversions |  260    260
Test Summary: | Pass  Total
Comparisons   |   86     86
Test Summary: | Pass  Total
Length        |   15     15
Test Summary:         | Pass  Total
Access and Iterations |   57     57
Test Summary: |  Pass  Total
Random        | 12448  12448
Test Summary: | Pass  Total
Find          |   33     33
Test Summary: | Pass  Total
Print         |    5      5
Test Summary: | Pass  Total
Show          |    5      5
Test Summary:   | Pass  Total
Transformations | 3848   3848
Test Summary: | Pass  Total
Mismatches    | 3200   3200
Test Summary: | Pass  Total
Matches       | 3200   3200
Test Summary:       | Pass  Total
De Bruijn Neighbors |    4      4
Test Summary: | Pass  Total
EveryKmer     |   14     14
Test Summary: | Pass  Total
SpacedKmers   |   14     14
Test Summary:      | Pass  Total
EveryCanonicalKmer |   18     18
Test Summary:        | Pass  Total
SpacedCanonicalKmers |   26     26
Test Summary: | Pass  Total
Translation   |   39     39
Test Summary: | Pass  Total
CodonSet      |  241    241
Test Summary:       | Pass  Total
Reverse translation |  148    148
```

2023-03-01 03:42 UTC, cjprybol commented on src/kmer.jl
> -        sym = convert(eltype(Kmer{A,K,N}), itr[i])
We're not able to index into an iterator, but we can iterate it at the index that we want

2023-03-01 03:43 UTC, cjprybol commented on src/revtrans.jl
> -struct Unsafe end
This is a duplicate definition https://github.com/BioJulia/Kmers.jl/blob/5dd8f8ff122e538f200582561defc836a3272046/src/kmer.jl#L15

2023-03-01 03:43 UTC, cjprybol commented on test/access.jl
> -        @test_throws BoundsError iterate(DNAKmer("ACTG"), -1)
Incorrect behavior per https://github.com/BioJulia/BioSequences.jl/pull/271

2023-03-01 03:44 UTC, cjprybol commented on test/construction_and_conversion.jl
> +    @test Kmers.kmertype(Kmer{DNAAlphabet{2},31})((i for i in rand(ACGT, 31))) isa Kmers.kmertype(Kmer{DNAAlphabet{2},31})
Specifically tests the example in https://github.com/BioJulia/BioSequences.jl/issues/270

2023-03-01 03:45 UTC, cjprybol commented on test/runtests.jl
> +    include("construction_and_conversion.jl")
clarify contents of the file, which tests both constructors and conversions

2023-03-03 14:09 UTC, kescobo requested changes
Rad, thanks for all the help with this package.! 

To be clear - it looks like the dependency you referenced at the beginning has been merged - is there a release of BioSequences that includes it yet? Once it is, this PR should include an update to the `[compat]` section of `Project.toml`.

2023-03-03 14:09 UTC, kescobo commented on src/kmer.jl
>          @inbounds for i in 1:n_per_chunk
Not critical, but I think `for i in 1:x` is starting to be considered gauche due to things like offset arrays. Is there a way to do this with `firstindex` or similar (only if it doesn't require bending over backwards).

2023-03-03 14:09 UTC, kescobo commented on test/access.jl
> +        @test iterate(DNAKmer("ACTG"), -1) === nothing
```suggestion
        @test isnothing(iterate(DNAKmer("ACTG"), -1))
```

2023-03-03 14:09 UTC, kescobo commented on test/access.jl
>          @test iterate(RNAKmer("ACUG"), 1)  !== nothing
```suggestion
        @test !isnothing(iterate(RNAKmer("ACUG"), 1))
```
etc.

2023-03-08 15:40 UTC, cjprybol commented
> Rad, thanks for all the help with this package.!

Glad to help, thanks for the assistance with the PRs! 

> To be clear - it looks like the dependency you referenced at the beginning has been merged - is there a release of BioSequences that includes it yet? Once it is, this PR should include an update to the `[compat]` section of `Project.toml`.

I don't see a new release yet but happy to update the compat once one is

2023-03-09 15:05 UTC, kescobo commented on test/access.jl
> +        @test iterate(RNAKmer("ACUG"), 0) === nothing
Can we update all of these? My apologies - I didn't notice before that you were copying the style of tests that were already there. I think either revert my suggestion above, or change them all.

2023-03-09 15:06 UTC, kescobo commented
@jakobnissen is there something holding back a release of BioSequences with https://github.com/BioJulia/BioSequences.jl/pull/271 ? I'm happy to do it, but wanted to double check.

2023-03-09 15:38 UTC, jakobnissen commented
Nope, let's cut a release. Also nice to get the other changes since last release. They're all bugfixes, so it can be a patch release, 3.1.3.

2023-03-09 18:40 UTC, kescobo commented
https://github.com/JuliaRegistries/General/pull/79281

@cjprybol Once that gets merged, I think bump the compat entry, which should also re-run the tests, and then I think it will be good to go

2023-04-10 18:41 UTC, kescobo approved these changes

2023-04-10 18:41 UTC, kescobo commented on test/access.jl
> +        @test !isnothing(iterate(RNAKmer("ACUG"), 1))
```suggestion
        @test iterate(RNAKmer("ACUG"), 1) !== nothing
```

don't want to just change the new one, my bad.

2023-04-11 22:36 UTC, merged

2023-04-11 23:21 UTC, cjprybol commented
Thanks for finishing this off @SabrinaJaye, and thanks for the helpful reviews @kescobo!